### ISSUE TITLE
 Idempotent issue with block append

### ISSUE THREAD

**Issue by drodrigues3** [minamijoyo/hcledit#32] opened 2021-08-20 19:51 UTC
When I ran the command below against the same file multiple times, this creates multiples blocks

```
hcledit -f elb.tf  -u block append resource.aws_lb.api-aws access_logs
```

elb.tf
``` 
resource "aws_lb" "api-aws" {
  enable_cross_zone_load_balancing = false
  internal                         = true
  load_balancer_type               = "network"
  name                             = "api-aws"
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1a.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1b.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1c.id
  }
}
```

#First interaction result

```
resource "aws_lb" "api-aws" {
  enable_cross_zone_load_balancing = false
  internal                         = true
  load_balancer_type               = "network"
  name                             = "api-aws"
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1a.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1b.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1c.id
  }
  access_logs {
  }
}
```

#Second interaction result

```
resource "aws_lb" "api-aws" {
  enable_cross_zone_load_balancing = false
  internal                         = true
  load_balancer_type               = "network"
  name                             = "api-aws"
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1a.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1b.id
  }
  subnet_mapping {
    subnet_id = data.aws_subnet.sa-east-1c.id
  }
  access_logs {
  }
  access_logs {
  }
}
```

And goes on

Is it expected for this component?

**Comment by minamijoyo** [comment] 2021-08-21 02:12
It's intentional because having multiple blocks as the same name is valid in the HCL specification and there is no way to check what is valid in the application level without knowing the specific application schema.

**Comment by minamijoyo** [comment] 2023-01-05 02:18
It is working as intended, and I have no intention of modifying the current behavior, so I'm closing it. Thanks!

**Closed by minamijoyo** 2023-01-05 02:18 UTC
