### ISSUE TITLE
How to edit an attribute?

### ISSUE THREAD

**Issue by infraredgirl** [minamijoyo/hcledit#60] opened 2022-08-30 18:07 UTC
Given the following config:
```
a = {
  b = "c"
}
```
I'd like to add another key/value pair to the `a` attribute, so that it ends up looking like this:
```
a = {
  b = "c"
  d = "e"
}
```
The type of `d` could be arbitrary, so instead of `"e"`, we could have, e.g. `1`, `true`, or `["e", "f"]`.

Is there a way to achieve this with `hcledit`?

**Comment by minamijoyo** [comment] 2022-09-01 02:01
Duplicates https://github.com/minamijoyo/hcledit/issues/44#issuecomment-1040292871
Currently, we cannot edit a value inside an object due to technical limitations of the hclwrite package in the upstream hcl library we depend on.

**Comment by minamijoyo** [comment] 2023-01-05 02:27
Closed this as duplicate of #44, which is also closed as duplicate of #28.

**Closed by minamijoyo** 2023-01-05 02:27 UTC
